live_config_reload = true
working_directory = "None"
#Themes --
import = [
 # "~/.config/alacritty/catppuccin-mocha.toml",
 # "~/.config/alacritty/nordic.toml",
  "~/.cache/wal/colors-alacritty.toml",
]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"
